name: Build Wails App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install
        shell: bash

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails App (Windows)
        if: matrix.os == 'windows-latest'
        run: wails build -platform windows/amd64
        shell: cmd

      - name: Build Wails App (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: wails build -platform linux/amd64
        shell: bash

      - name: Upload Windows Build Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: wails-windows
          path: build/bin/*.exe

      - name: Upload Linux Build Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: wails-linux
          path: build/bin/*
